### ISSUE TITLE
v.12 on GNOME 42: UserWidget is not a constructor

### ISSUE THREAD

**Issue by iadegesso** [pawelswiszcz/Avatar-Gnome-Shell-Extension#17]
If I upgrade from v.11 to v.12 on my Gentoo running GNOME 42, I get the 'UserWidget is not a constructor' error message (see the attached picture).

Iade

![error](https://user-images.githubusercontent.com/5804075/161448141-9c812988-bdbc-4b51-a747-38b9d054bed1.png)

**Comment by pawelswiszcz** [comment]
Hi 
Thanks for the issue. I'll check. To be sure, did You restart the gnome shell (ALT+F2+r)?

**Comment by iadegesso** [comment]
Yes, I did :)


Iade

Il dom 3 apr 2022, 23:24 Paweł Świszcz ***@***.***> ha
scritto:

**Comment by pawelswiszcz** [comment]
Hi 

I've added some fixes. Could You update the extension and check again?

**Comment by iadegesso** [comment]
> Hi
> 
> I've added some fixes. Could You update the extension and check again?

It seems to work... let me try it after a fresh boot. Thanks.


Iade
