### ISSUE TITLE
"Please ad.. " message

### ISSUE THREAD

**Issue by brunnogama** [pawelswiszcz/Avatar-Gnome-Shell-Extension#19]
Hey man.
After this last update I have this message on menu (see screenshot).
I dont have media option enabled and I'm using Gnome 41.5 on Fedora 35.
![error](https://user-images.githubusercontent.com/30611127/161875563-e630d5ae-b684-4fa9-be0a-31641748306b.png)

Thanx for your great work!

**Comment by pawelswiszcz** [comment]
Hello!
This message "Please add the Top image in extension properties" is from a new feature Top Image. In preferences page you can pick an image to be shown in the panel. It can be turn off in settings. I'll try to fix this message to be more visible.

**Comment by pawelswiszcz** [comment]
The label should be more visibled
