### ISSUE TITLE
Mpris section container is visible even if no Media is playing.

### ISSUE THREAD

**Issue by Zetta1-Reid0** [pawelswiszcz/Avatar-Gnome-Shell-Extension#21]
Gnome 42

![Снимка на екрана на 2022-04-21 22-29-25](https://user-images.githubusercontent.com/79805086/164614494-c7575ad8-b6f3-4cda-8469-8524e28a280e.png)

**Comment by Zetta1-Reid0** [comment]
This PR should fix it : #22

**Comment by pawelswiszcz** [comment]
@Zetta1Reid0 
I think It could be done like this:
When menu is opened (somehow bind the function to signal opened) check how many players are in `this._mediaSection._players;`. If `0 === count(this._mediaSection._players)` set `height = 0` on Mpris container

**Comment by Zetta1-Reid0** [comment]
Ofcourse why didn't I think of that. It can be bound to 'open-state-changed' signal of aggregate menu.Also you don't need count this._mediaSection._players is a map so this should be more correct: if this._mediaSection._players.size() === 0 .  About height IDK, It sounds it could create a problem. Better just hide container or show it. Will get on that when I have time.

**Comment by Zetta1-Reid0** [comment]
Ok so there is a little problem. Chrome doesn't free the d-bus connection so players count remains at 1 so container doesn't hide. (atleast for me). So container won't hide untill Chrome is closed.Fix works good on the other mpris compatible players I tested.

**Comment by pawelswiszcz** [comment]
> Ok so there is a little problem. Chrome doesn't free the d-bus connection so players count remains at 1 so container doesn't hide. (atleast for me). So container won't hide untill Chrome is closed.Fix works good on the other mpris compatible players I tested.

Could You send a PR? I'll check. Maybe for chrome it we can be fixed later?

**Comment by Zetta1-Reid0** [comment]
Well most browsers nowadays are based on chrome, so i think they will behave same way. And adding exceptions for all of them is not a good workaround.

**Comment by pawelswiszcz** [comment]
> Well most browsers nowadays are based on chrome, so i think they will behave same way. And adding exceptions for all of them is not a good workaround.

In my gnome 41 Chrome and chromium-browser Vivaldi works correctly
