### ISSUE TITLE
It doesn't look anything like your screenshots

### ISSUE THREAD

**Issue by hrqmonteiro** [pawelswiszcz/Avatar-Gnome-Shell-Extension#25]
![Screenshot from 2022-09-03 18-56-21](https://user-images.githubusercontent.com/17055027/188288803-9c1d4a78-d1d3-48a7-a18e-c61941284621.png)

How is this anything close to the screenshot you presented in the repo?

![image](https://user-images.githubusercontent.com/17055027/188288812-c8c5aebb-ad17-436d-9c60-5a63d1ad9d73.png)

I never saw something so far from the presentation as this extension, my dude. It is ugly as hell in my machine.

**Comment by pawelswiszcz** [comment]
Hello @hrqmonteiro 
The extension is based on the current style of the system. Please try to change the system style or open the add-on's preferences and try to change the avatar size, button size, menu length, or positions. You can also disable the Top Image or add your own. My current extension looks like this:    

![Zrzut ekranu z 2022-09-04 12-12-32](https://user-images.githubusercontent.com/1814271/188311910-772bbb96-bac1-4eb9-ac2e-1ff4ce23820a.png)
