### ISSUE TITLE
Add support for gnome 43

### ISSUE THREAD

**Issue by pawelswiszcz** [pawelswiszcz/Avatar-Gnome-Shell-Extension#26]
Add support for gnome 43

**Comment by bitseater** [comment]
If i can help: when i use `quickSettings`  instead `aggregateMenu` the extension is working for me (Debian unstable + gnome-shell 43.0)

Some references at [GJS guide](https://gjs.guide/extensions/upgrading/gnome-shell-43.html#quick-settings)

**Comment by bern6** [comment]
bitseater,
perfect, works for me
thank you

**Comment by pawelswiszcz** [comment]
Hello @bitseater and @bern6 
Could You check PR  https://github.com/pawelswiszcz/Avatar-Gnome-Shell-Extension/pull/27 on your Gnome43 and add the screenshot?
