### ISSUE TITLE
media center shows nothing

### ISSUE THREAD

**Issue by chenxiex** [pawelswiszcz/Avatar-Gnome-Shell-Extension#28]
![screenshot](https://alspace.anlor.top/ResourceBed/747c3df0b56bd11d367a5aa8d11eb617.png)
I was playing media using firefox, but the media center shows nothing but an empty box.
Gnome 43, manjaro linux.

**Comment by pawelswiszcz** [comment]
@chenxiex Thanks for using Avatar Gnome extension. Sorry for that error. It should be fixed in 20 version.

**Comment by chenxiex** [comment]
It works fine. Thanks for your excellent work.
