### ISSUE TITLE
the big avatar is not centered in gnome 43 quick settings

### ISSUE THREAD

**Issue by Kazy-jew** [pawelswiszcz/Avatar-Gnome-Shell-Extension#30]
more conspicuous if enabled [this extension](https://extensions.gnome.org/extension/5527/compact-quick-settings/) in gnome 43
(may need to disable and re-enable avatar to make into effect)

**Comment by pawelswiszcz** [comment]
Hello @Kazy-jew 
Could You provide more details? Screenshot? On my virtualbox it looks quite ok. 

![Zrzut ekranu z 2023-01-08 15-36-16](https://user-images.githubusercontent.com/1814271/211202256-394716d3-bb8c-4448-a718-e2908ad40bf7.png)

**Comment by pawelswiszcz** [comment]
@Kazy-jew 
Hello! It should be fixed in next release.
