### ISSUE TITLE
my painel stopped showing the avatar after 1 week

### ISSUE THREAD

**Issue by gutachi** [pawelswiszcz/Avatar-Gnome-Shell-Extension#6]
I dont know what happened but it suddenly stopped showing the image, and on the place of the avatar stayed a empty space that when i click nothing happens. (Sorry if i wrote something wrong, I'm not native)

**Comment by gutachi** [comment]
![erro_extens_avatar](https://user-images.githubusercontent.com/56056363/154302683-44bbf54f-4484-479f-a0a6-dc85b17d8648.png)
![image](https://user-images.githubusercontent.com/56056363/154302806-c3822128-947c-49f3-b940-9687617e5a45.png)
![image](https://user-images.githubusercontent.com/56056363/154302887-bd94d062-84fe-4174-82cf-9422497f6df6.png)

**Comment by pawelswiszcz** [comment]
Hi @GustavoChiato15 

Thanks for using my extension. Sorry for the inconvenience :/ 

Could You check logs:
```
journalctl -f -o cat /usr/bin/gnome-shell
```
maybe there is an error that might help do diagnose this. What is Your gnome version? Strange that Technical Details are empty.

**Comment by pawelswiszcz** [comment]
Maybe try also to remove the extension and install it again. Try ALT + F2 and r (restart gnome shell)

**Comment by pawelswiszcz** [comment]
Close this issue due to no answer
