### ISSUE TITLE
Request: Ability to override and lock panel width

### ISSUE THREAD

**Issue by bluesaka111** [pawelswiszcz/Avatar-Gnome-Shell-Extension#8]
Reason: Many gnome / gtk theme will set panel width at fixed size and that not enough space to render content from Avatar extension.
Image : https://photos.app.goo.gl/C1XUZrdDoMY4KeeK9
Version: Garuda Linux - GNOME - Avatar 7

**Comment by pawelswiszcz** [comment]
@bluesaka111 

Thanks for the issue! This feature was added in last update ;) due too last Your comment in extensions page. Please look into settings on position "**set custom panel menu width**"  https://github.com/pawelswiszcz/Avatar-Gnome-Shell-Extension/blob/master/assets/options.png
